// 演员

export const ACTOR_SEXTAGS = "ACTOR_SEXTAGS"
export const ACTOR_AGETAGS = "ACTOR_AGETAGS"
export const ACTOR_NATIONALTAGS = "ACTOR_NATIONALTAGS"
export const ACTOR_HOBBYTAGS = "ACTOR_HOBBYTAGS"
export const ACTOR_HOBBYLIST = "ACTOR_HOBBYLIST"
export const ACTOR_COUNTRYLIST = "ACTOR_COUNTRYLIST"
export const ACTOR_ACTORLIST = "ACTOR_ACTORLIST"
export const ACTOR_PAGENUM = "ACTOR_PAGENUM"
export const ACTOR_PAGESIZE = "ACTOR_PAGESIZE"
export const ACTOR_TOTAL = "ACTOR_TOTAL"

